baseURL = "https://blog.topasm.me/"
title = "Topasm blog"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"

[minify]
disableXML = true
minifyOutput = true

[[menu.main]]
name = "Archive"
url = "archives/"
weight = 5

[[menu.main]]
name = "Search"
url = "search/"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 10

[outputs]
    home = [
        "HTML",
        "RSS",
        "JSON"
    ]

[params]
env = "production"
title = "topasm|robotics"
description = "personal blog"
author = "Kim"
DateFormat = "January 2, 2006"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

[params.label]
text = "Topasm | blog"
icon = "/Iconrobot.png"
iconHeight = 35



[params.homeInfoParams]
Title = "안녕하세요 Hello👋"
Content = """
Mechanical engineering Bachelor degree 3nd year | Interest in Robotics

-기계공학과 3학년 학생이며 로봇에 관심이 많습니다.

"""
[[params.socialIcons]]
name = "github"
url = "https://github.com/Topasm"

[params.analytics.google]
SiteVerificationTag = "XYZabc"
